"""empty message

Revision ID: 07857c72f330
Revises: f5a3e4e31b6c
Create Date: 2020-05-18 23:07:23.791193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07857c72f330'
down_revision = 'f5a3e4e31b6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    # ### end Alembic commands ###
