"""empty message

Revision ID: 29a2c190afce
Revises: 48615a11c7c7
Create Date: 2020-05-20 16:58:40.411617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a2c190afce'
down_revision = '48615a11c7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('bookcover', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'bookcover')
    # ### end Alembic commands ###
