"""empty message

Revision ID: 39250dedb648
Revises: 4ede07f3f210
Create Date: 2020-05-20 18:40:38.118259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39250dedb648'
down_revision = '4ede07f3f210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('synopsis', sa.String(), nullable=True))
    op.drop_column('books', 'countries_book_banned')
    op.drop_column('books', 'blurb')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('blurb', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('countries_book_banned', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'synopsis')
    # ### end Alembic commands ###
