"""empty message

Revision ID: 48615a11c7c7
Revises: 07857c72f330
Create Date: 2020-05-19 11:07:43.071730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48615a11c7c7'
down_revision = '07857c72f330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_country_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'country_id')
    op.drop_table('countries')
    op.drop_constraint('authors_book_id_fkey', 'authors', type_='foreignkey')
    op.drop_column('authors', 'book_id')
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('books', sa.Column('countries_book_banned', sa.String(), nullable=True))
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_country_id_fkey', 'books', 'countries', ['country_id'], ['id'])
    op.drop_column('books', 'countries_book_banned')
    op.drop_column('books', 'author_id')
    op.add_column('authors', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('authors_book_id_fkey', 'authors', 'books', ['book_id'], ['id'])
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='countries_pkey')
    )
    # ### end Alembic commands ###
