"""empty message

Revision ID: 5b429c982831
Revises: 39250dedb648
Create Date: 2020-05-20 18:56:40.497759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b429c982831'
down_revision = '39250dedb648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('authors', 'author_name')
    op.add_column('country', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('country', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('country', 'name')
    op.add_column('authors', sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('authors', 'name')
    # ### end Alembic commands ###
