"""empty message

Revision ID: 790f50ad3980
Revises: 5b429c982831
Create Date: 2020-05-20 20:52:24.190353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790f50ad3980'
down_revision = '5b429c982831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('dob', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'dob')
    # ### end Alembic commands ###
