"""empty message

Revision ID: 98a8aa907d5d
Revises: 9e00b17850c3
Create Date: 2020-05-18 17:20:09.026632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a8aa907d5d'
down_revision = '9e00b17850c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('People')
    op.add_column('books', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'countries', ['country_id'], ['id'])
    op.drop_constraint('countries_author_id_fkey', 'countries', type_='foreignkey')
    op.drop_constraint('countries_book_id_fkey', 'countries', type_='foreignkey')
    op.drop_column('countries', 'book_id')
    op.drop_column('countries', 'author_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('countries', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('countries_book_id_fkey', 'countries', 'books', ['book_id'], ['id'])
    op.create_foreign_key('countries_author_id_fkey', 'countries', 'authors', ['author_id'], ['id'])
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'country_id')
    op.create_table('People',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"People_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('catchphrase', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('thing', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='People_pkey')
    )
    # ### end Alembic commands ###
