"""empty message

Revision ID: 9e00b17850c3
Revises: 5e48b86d6d13
Create Date: 2020-05-18 10:13:08.959875

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9e00b17850c3'
down_revision = '5e48b86d6d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('book_id', sa.Integer(), nullable=True))
    #op.create_foreign_key(None, 'authors', 'books', ['book_id'], ['id'])
    op.add_column('countries', sa.Column('author_id', sa.Integer(), nullable=True))
    op.add_column('countries', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'countries', 'authors', ['author_id'], ['id'])
    op.create_foreign_key(None, 'countries', 'books', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.drop_constraint(None, 'countries', type_='foreignkey')
    op.drop_column('countries', 'book_id')
    op.drop_column('countries', 'author_id')
    op.drop_constraint(None, 'authors', type_='foreignkey')
    op.drop_column('authors', 'book_id')
    # ### end Alembic commands ###
