"""empty message

Revision ID: b55588f1c5d1
Revises: 1f35e1143404
Create Date: 2020-09-24 17:24:39.434666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b55588f1c5d1'
down_revision = '1f35e1143404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banned_book', sa.Column('end_date_year', sa.Integer(), nullable=True))
    op.add_column('banned_book', sa.Column('start_date_year', sa.Integer(), nullable=True))
    op.drop_column('banned_book', 'start_date')
    op.drop_column('banned_book', 'end_date')
    op.add_column('book', sa.Column('published_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'published_date')
    op.add_column('banned_book', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('banned_book', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('banned_book', 'start_date_year')
    op.drop_column('banned_book', 'end_date_year')
    # ### end Alembic commands ###
