"""empty message

Revision ID: ea0b58fe18e0
Revises: 29a2c190afce
Create Date: 2020-05-20 17:43:44.946177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0b58fe18e0'
down_revision = '29a2c190afce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_cover', sa.String(), nullable=True))
    op.drop_column('books', 'bookcover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('bookcover', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('books', 'book_cover')
    # ### end Alembic commands ###
