"""empty message

Revision ID: f3ac44e7e2f3
Revises: 790f50ad3980
Create Date: 2020-05-21 11:21:45.996506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ac44e7e2f3'
down_revision = '790f50ad3980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('about', sa.String(), nullable=True))
    op.add_column('banned_details', sa.Column('reason_given', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banned_details', 'reason_given')
    op.drop_column('authors', 'about')
    # ### end Alembic commands ###
