"""empty message

Revision ID: f5a3e4e31b6c
Revises: 98a8aa907d5d
Create Date: 2020-05-18 21:54:05.637496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a3e4e31b6c'
down_revision = '98a8aa907d5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test', sa.Column('country_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'country_name')
    # ### end Alembic commands ###
